Repository h0ngwon/Camperspot, pull requests merged in 2024-01, with the labels that each got.

#5 feat: 헤더에 개발 페이지 라우팅 (#1)
  .github/PULL_REQUEST_TEMPLATE.md
  src/app/api/db.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Header.tsx
  src/components/Reservation.tsx
  src/components/header.module.css
  src/styles/globals.css
  src/styles/reset.css
  src/types/supabase.d.ts
Labels: 기능

#11 fix: 예약정보 데이터 구조 변경
  src/app/camp/detail/[id]/_components/ReservationModal.tsx
  src/types/reservation.ts
Labels: fix

#14 Feat/reservation 홈에서 예약 클릭 시 주소 이동 오류 수정
  src/app/camp/detail/[id]/@modal/(.)reservation/page.tsx
  src/app/camp/detail/[id]/@modal/default.tsx
  src/app/camp/detail/[id]/layout.tsx
Labels: bug, fix

#15 [Feat/auth] 인증 / 인가 기능
  src/app/api/auth/[...nextauth]/route.ts
  src/app/auth/signin/_components/SigninForm.tsx
  src/app/auth/signin/_components/SocialButton.tsx
  src/app/auth/signin/_styles/SigninForm.module.css
  src/app/auth/signin/_styles/SigninPage.module.css
  src/app/auth/signin/_styles/SocialButton.module.css
  src/app/auth/signin/page.tsx
  src/app/auth/signup/_components/SignupForm.tsx
  src/app/auth/signup/_styles/SignupForm.module.css
  src/app/auth/signup/page.tsx
  src/app/layout.tsx
  src/components/Header.tsx
  src/middleware.ts
  src/types/supabase.ts
Labels: 기능, fix

#17 Feat/auth
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/app/auth/signin/page.tsx
  src/app/auth/signup/_components/SignupForm.tsx
  src/middleware.ts
  src/types/next-auth.d.ts
  yarn.lock
Labels: fix

#18 Feat/create camp 캠핑장 등록/캠핑존 등록
  package.json
  src/app/company/[id]/manage_camp/add/page.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/AddressModal.tsx
  src/app/company/[id]/manage_camp/add_camp/_styles/CampForm.module.css
  src/app/company/[id]/manage_camp/add_camp/_styles/SearchAddress.module.css
  src/app/company/[id]/manage_camp/add_camp/page.tsx
  src/app/company/[id]/manage_camp/add_camp_area/_styles/CampAreaForm.module.css
  src/app/company/[id]/manage_camp/add_camp_area/page.tsx
  src/components/Header.tsx
  src/hooks/useInput.ts
  src/types/camp.ts
  src/types/supabase.ts
  yarn.lock
Labels: 기능

#20 Feat/manage company 해시태그 기능 추가
  next.config.js
  src/app/company/[id]/_components/CompanyHeader.tsx
  src/app/company/[id]/manage_camp/[camp_id]/add_camp_area/_styles/CampAreaForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/add_camp_area/page.tsx
  src/app/company/[id]/manage_camp/add_camp/page.tsx
  src/app/company/[id]/manage_company_info/page.tsx
Labels: 기능

#22 Feat/camp 캠프 둘러보기 페이지
  .github/PULL_REQUEST_TEMPLATE.md
  memo.txt
  next.config.js
  package.json
  src/app/api/camp/route.ts
  src/app/camp/_components/A.tsx
  src/app/camp/_components/CampFilter.tsx
  src/app/camp/_components/CampList.tsx
  src/app/camp/_components/Hashtag.tsx
  src/app/camp/_components/Like.tsx
  src/app/camp/_components/PageController.tsx
  src/app/camp/_components/Photo.tsx
  src/app/camp/_styles/Camp.module.css
  src/app/camp/_styles/CampList.module.css
  src/app/camp/_styles/PageController.module.css
  src/app/camp/_styles/Photo.module.css
  src/app/camp/page.tsx
  src/app/page.tsx
  src/asset/abc.png
  src/components/Header.tsx
  src/components/Spacer.tsx
  src/middleware.ts
  src/types/supabaseSchema.ts
  yarn.lock
Labels: 기능

#23 [feat/manage-reservation] 예약 관리 기능 구현
  src/app/_components/AlertModal.tsx
  src/app/_components/ConfirmModal.tsx
  src/app/_styles/ConfirmModal.module.css
  src/app/camp/detail/[id]/_components/ReservationForm.tsx
  src/app/company/[id]/manage_reservation/_components/Reservation.tsx
  src/app/company/[id]/manage_reservation/_components/ReservationList.tsx
  src/app/company/[id]/manage_reservation/_lib/reservation.ts
  src/app/company/[id]/manage_reservation/_styles/Reservation.module.css
  src/app/company/[id]/manage_reservation/_styles/ReservationList.module.css
  src/app/company/[id]/manage_reservation/page.tsx
  src/components/Header.tsx
  src/types/reservation.ts
Labels: 기능

#26 [feat/manage-reservation] 예약 관리 기능 구현
  src/app/_utils/regex.ts
  src/app/company/[id]/manage_reservation/_components/ReservationList.tsx
  src/app/company/[id]/manage_reservation/_lib/reservation.ts
  src/app/company/[id]/manage_reservation/_styles/ReservationList.module.css
Labels: bug, 기능, fix

#29 Feat/manage-reservation : 일부 코드 수정
  src/app/camp/detail/[id]/reservation/page.tsx
  src/app/company/[id]/manage_reservation/_styles/ReservationList.module.css
Labels: fix

#31 Feat/home 메인페이지 기능구현
  .gitignore
  next.config.js
  src/app/_components/CampCard.tsx
  src/app/_components/CampCarousel.tsx
  src/app/_components/Carousel.tsx
  src/app/_components/Main.tsx
  src/app/_components/PopularCamp.tsx
  src/app/_components/PopularCommunity.tsx
  src/app/_components/RegionCarousel.tsx
  src/app/_styles/CampCard.module.css
  src/app/_styles/Carousel.module.css
  src/app/_styles/Main.module.css
  src/app/_styles/RegionFiltter.module.css
  src/app/camp/_components/CampList.tsx
  src/app/camp/search/page.tsx
  src/app/page.tsx
  src/asset/icon_address.svg
Labels: 기능, UI

#33 [Feat/profile] 프로필 불러오기 및 모달
  next.config.js
  src/app/_components/AuthSession.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/profile/[id]/route.ts
  src/app/layout.tsx
  src/app/profile/[id]/_components/Content.tsx
  src/app/profile/[id]/_components/Profile.tsx
  src/app/profile/[id]/_components/Sidebar.tsx
  src/app/profile/[id]/_lib/getUserData.ts
  src/app/profile/[id]/_styles/Content.module.css
  src/app/profile/[id]/_styles/MypageLayout.module.css
  src/app/profile/[id]/_styles/Profile.module.css
  src/app/profile/[id]/_styles/Sidebar.module.css
  src/app/profile/[id]/layout.tsx
  src/app/profile/[id]/page.tsx
  src/components/Header.tsx
  src/components/Modal.tsx
  src/components/ModalPortal.tsx
  src/middleware.ts
  src/store/modal.ts
  src/styles/Modal.module.css
  src/types/auth.ts
Labels: 기능

#35 Feat/header 헤더기능구현
  package.json
  src/app/_components/Calendar.tsx
  src/app/_components/CampCard.tsx
  src/app/_components/Main.tsx
  src/app/_components/People.tsx
  src/app/_components/RealHeader.tsx
  src/app/_components/SearchBar.tsx
  src/app/_styles/Calendar.module.css
  src/app/_styles/RealHeader.module.css
  src/app/_styles/SearchBar.module.css
  src/app/_utils/date.ts
  src/app/camp/detail/[id]/_components/DetailCampZone.tsx
  src/app/camp/detail/[id]/_svg/ReviewStarSvg.tsx
  src/app/camp/detail/[id]/_svg/Star.tsx
  src/app/layout.tsx
  src/asset/AddressSvg.tsx
  src/asset/Calendar.svg
  src/asset/CommunitySvg.tsx
  src/asset/MyProfileSvg.tsx
  src/asset/SearchSvg.tsx
  src/asset/abc.png
  src/asset/icon_address.svg
  src/asset/logo.png
  src/asset/logo2.png
  yarn.lock
Labels: 기능, UI

#37 Feat/manage company 등록한 캠핑장 added_camp 페이지에 뿌려주기 및 add_camp페이지에서 params id 가져오기
  next.config.js
  src/app/company/[id]/_components/CompanyHeader.tsx
  src/app/company/[id]/layout.tsx
  src/app/company/[id]/manage_camp/[camp_id]/add_camp_area/_styles/CampAreaForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/_components/CampAreaModal.tsx
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/_styles/CampAreaForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/page.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/AddForm.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/CampPicture.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/CheckInOut.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Facility.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Hashtag.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Layout.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/SearchAddress.tsx
  src/app/company/[id]/manage_camp/add_camp/page.tsx
  src/app/company/[id]/manage_camp/added_camp/_styles/Camp.module.css
  src/app/company/[id]/manage_camp/added_camp/page.tsx
  src/app/company/[id]/manage_company_info/page.tsx
  src/app/company/[id]/manage_company_user_info/page.tsx
  src/app/company/[id]/page.tsx
  src/asset/ph_plus.png
  src/components/Header.tsx
Labels: 기능, fix

#38 Feat/manage company Company Header에 페이지 이동 기능
  src/app/company/[id]/_components/CompanyHeader.tsx
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/_components/CampAreaModal.tsx
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/page.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/AddForm.tsx
Labels: 기능, fix

#39 feat/manage-company fix:레이아웃 정리 및 css (진행중)
  src/app/company/[id]/_components/CompanyHeader.tsx
  src/app/company/[id]/_styles/CompanyHeader.module.css
  src/app/company/[id]/_styles/CompanyLayout.module.css
  src/app/company/[id]/layout.tsx
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/_components/CampAreaModal.tsx
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/_styles/CampAreaForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/page.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/CampPicture.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Layout.tsx
  src/app/company/[id]/manage_camp/add_camp/_styles/CampForm.module.css
  src/asset/closeBtn.png
  src/components/Header.tsx
Labels: UI

#40 [Feat/reservation modal] 예약하기 기능 수정
  src/app/camp/detail/[id]/_components/Calendar.tsx
  src/app/camp/detail/[id]/_components/DetailCampZone.tsx
  src/app/camp/detail/[id]/_components/ReservationForm.tsx
  src/app/camp/detail/[id]/_components/ReservationModal.tsx
  src/app/camp/detail/[id]/_styles/ReservationForm.module.css
  src/app/camp/detail/[id]/_styles/ReservationModal.module.css
  src/app/camp/detail/[id]/reservation/page.tsx
  src/app/company/[id]/manage_reservation/_lib/reservation.ts
  src/types/reservation.ts
Labels: 기능, UI

#42 Fix/profile 프로필 페이지 수정
  next.config.js
  src/app/api/profile/[id]/route.ts
  src/app/community/[id]/create/page.tsx
  src/app/profile/[id]/_components/Profile.tsx
  src/app/profile/[id]/_components/ProfileModifyForm.tsx
  src/app/profile/[id]/_lib/modifyUserData.ts
  src/app/profile/[id]/_styles/ProfileModifyForm.module.css
  src/components/Modal.tsx
  src/hooks/useInput.ts
  src/styles/Modal.module.css
Labels: fix

#43 Feat/search 검색결과 페이지 구현중
  next.config.js
  src/app/_components/CampCard.tsx
  src/app/_components/CampCarousel.tsx
  src/app/_components/Carousel.tsx
  src/app/_components/Header.tsx
  src/app/_components/Main.tsx
  src/app/_components/PopularCamp.tsx
  src/app/_components/RealHeader.tsx
  src/app/_components/RegionCarousel.tsx
  src/app/_components/SearchBar.tsx
  src/app/_styles/CampCard.module.css
  src/app/_styles/CampCarousel.module.css
  src/app/_styles/Carousel.module.css
  src/app/_styles/Header.module.css
  src/app/_styles/RegionFiltter.module.css
  src/app/camp/_components/A.tsx
  src/app/camp/_components/CampList.tsx
  src/app/camp/_components/Hashtag.tsx
  src/app/camp/_styles/Camp.module.css
  src/app/camp/_styles/CampList.module.css
  src/app/camp/page.tsx
  src/app/camp/search/page.tsx
  src/app/layout.tsx
  src/asset/CommunitySvg.tsx
  src/asset/logOut.png
  src/asset/main_banner_1.png
  src/asset/main_banner_2.png
  src/asset/main_banner_3.png
  src/asset/main_banner_4.png
  src/components/Header.tsx
  src/components/header.module.css
  src/styles/globals.css
Labels: 기능, UI

#44 Feat/mypage reservation 마이페이지 예약 현황 조회
  package.json
  src/app/_components/AlertModal.tsx
  src/app/layout.tsx
  src/app/profile/[id]/_components/ReservationDetail.tsx
  src/app/profile/[id]/_components/ReservationDetailModal.tsx
  src/app/profile/[id]/_components/ReservationList.tsx
  src/app/profile/[id]/_lib/getUserReservation.ts
  src/app/profile/[id]/_styles/ReservationDetail.module.css
  src/app/profile/[id]/_styles/ReservationDetailModal.module.css
  src/app/profile/[id]/_styles/ReservationList.module.css
  src/app/profile/[id]/reservation/page.tsx
  src/types/reservation.ts
  yarn.lock
Labels: 기능

#45 Style/main 메인페이지 디자인 수정
  src/app/_components/CampCard.tsx
  src/app/_components/CampCarousel.tsx
  src/app/_components/Header.tsx
  src/app/_components/Main.tsx
  src/app/_components/PopularCamp.tsx
  src/app/_components/RegionCarousel.tsx
  src/app/_components/SearchBar.tsx
  src/app/_lib/regions.ts
  src/app/_styles/CampCard.module.css
  src/app/_styles/Header.module.css
  src/app/_styles/RegionFiltter.module.css
  src/app/_styles/SearchBar.module.css
  src/app/api/camp/route.ts
  src/app/camp/_components/CampList.tsx
  src/app/camp/_components/Hashtag.tsx
  src/app/camp/_components/Like.tsx
  src/app/camp/_components/PageController.tsx
  src/app/camp/_styles/CampList.module.css
  src/app/camp/page.tsx
  src/app/camp/search/page.tsx
  src/asset/region/강원.jpg
  src/asset/region/경기.jpg
  src/asset/region/경남.jpg
  src/asset/region/경북.jpg
  src/asset/region/광주.jpg
  src/asset/region/대구.jpg
  src/asset/region/대전.jpg
  src/asset/region/부산.jpg
  src/asset/region/서울.jpg
  src/asset/region/울산.jpg
  src/asset/region/인천.jpg
  src/asset/region/전남.jpg
  src/asset/region/전북.jpg
  src/asset/region/제주.jpg
  src/asset/region/충남.jpg
  src/asset/region/충북.jpg
  src/components/AddressSvg.tsx
  src/components/CommunitySvg.tsx
  src/components/MyProfileSvg.tsx
  src/components/SearchSvg.tsx
Labels: UI

#47 Feat/profile 프로필 수정 기능
  src/app/api/profile/[id]/route.ts
  src/app/profile/[id]/_components/ProfileModifyForm.tsx
  src/app/profile/[id]/_lib/modifyUserData.ts
Labels: 기능, fix

#48 Style/main 메인페이지 CSS 수정
  src/app/_components/CampCarousel.tsx
  src/app/_components/Header.tsx
  src/app/_components/RegionCarousel.tsx
  src/app/_styles/Header.module.css
  src/app/camp/_components/Photo.tsx
  src/app/community/_components/CommuPhotos.tsx
  src/asset/region/울산.jpg
  src/components/CarouselNextArrow.tsx
  src/components/CarouselPrevArrow.tsx
  src/styles/CarouselBtn.module.css
Labels: Style

#50 fix: 에러수정 svg 에러메세지 수정
  src/app/camp/_components/CampList.tsx
  src/app/camp/_styles/CampList.module.css
  src/app/camp/detail/[id]/_svg/LocationSvg.tsx
  src/app/camp/detail/[id]/_svg/ReviewStarSvg.tsx
  src/app/camp/detail/[id]/_svg/Star.tsx
Labels: fix

#51 [Fix/community] 글쓰기 버튼 이동
  src/app/community/_styles/Commu.module.css
  src/app/community/_svg/CreateSvg.tsx
  src/app/community/page.tsx
Labels: fix

#52 Feat/auth 소셜로그인 디자인 수정
  src/app/_components/Header.tsx
  src/app/api/profile/[id]/route.ts
  src/app/auth/signin/_components/KakaoButton.tsx
  src/app/auth/signin/_components/NaverButton.tsx
  src/app/auth/signin/_components/SocialButton.tsx
  src/app/auth/signin/_styles/KakaoButton.module.css
  src/app/auth/signin/_styles/NaverButton.module.css
  src/app/auth/signin/_styles/SigninPage.module.css
  src/app/auth/signin/page.tsx
  src/asset/ico_kakao.png
  src/asset/ico_naver.png
  src/middleware.ts
Labels: 기능

#53 [Fix/camp] 데이터 revalidate
  src/app/_components/PopularCamp.tsx
  src/app/camp/page.tsx
  src/app/camp/search/page.tsx
Labels: fix

#54 Feat/mypage reservation 예약현황 스타일 수정
  src/app/profile/[id]/_components/ReservationDetail.tsx
  src/app/profile/[id]/_components/ReservationDetailModal.tsx
  src/app/profile/[id]/_components/ReservationList.tsx
  src/app/profile/[id]/_styles/ReservationDetail.module.css
  src/app/profile/[id]/_styles/ReservationDetailModal.module.css
  src/app/profile/[id]/_styles/ReservationList.module.css
Labels: Style

#55 [Fix/profile] 프로필수정 (#24)
  package.json
  src/app/api/profile/[id]/route.ts
  src/app/profile/[id]/_components/Profile.tsx
  src/app/profile/[id]/_components/ProfileModifyForm.tsx
  yarn.lock
Labels: fix

#57 fix: middleware 수정 (#4)
  src/app/_components/Header.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/middleware.ts
  src/styles/Modal.module.css
Labels: fix

#58 [Feat/auth] 인증 / 인가 기능 완료
  next.config.js
  public/fonts/Pretendard-Black.woff2
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-ExtraBold.woff2
  public/fonts/Pretendard-ExtraLight.woff2
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  public/fonts/Pretendard-Thin.woff2
  public/fonts/PretendardVariable.woff2
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/signup/route.ts
  src/app/auth/signin/_components/KakaoButton.tsx
  src/app/auth/signin/_components/NaverButton.tsx
  src/app/auth/signin/_components/SigninForm.tsx
  src/app/auth/signin/_styles/KakaoButton.module.css
  src/app/auth/signin/_styles/NaverButton.module.css
  src/app/auth/signin/_styles/SigninForm.module.css
  src/app/auth/signin/_styles/SigninPage.module.css
  src/app/auth/signin/page.tsx
  src/app/auth/signup/_components/SignupForm.tsx
  src/app/auth/signup/_styles/SignupForm.module.css
  src/app/auth/signup/_styles/SignupPage.module.css
  src/app/auth/signup/page.tsx
  src/app/layout.tsx
  src/app/profile/[id]/_styles/Profile.module.css
  src/middleware.ts
  src/types/auth.ts
Labels: 기능

#61 Feat/mypage reservation 예약관리 페이지 스타일 수정
  src/app/profile/[id]/_components/ReservationDetail.tsx
  src/app/profile/[id]/_components/ReservationDetailModal.tsx
  src/app/profile/[id]/_components/ReservationList.tsx
  src/app/profile/[id]/_components/Sidebar.tsx
  src/app/profile/[id]/_styles/ReservationDetail.module.css
  src/app/profile/[id]/_styles/ReservationDetailModal.module.css
  src/app/profile/[id]/_styles/ReservationList.module.css
  src/app/profile/[id]/_styles/Sidebar.module.css
  src/components/Modal.tsx
  src/components/ModalCloseSvg.tsx
  src/components/ReservationArrowSvg.tsx
  src/styles/Modal.module.css
  src/styles/globals.css
Labels: UI, Style

#63 [FIX/profile] 모달 수정
  src/app/auth/signin/_components/SigninForm.tsx
  src/app/auth/signup/_components/SignupForm.tsx
  src/app/profile/[id]/_components/Profile.tsx
  src/app/profile/[id]/_styles/Profile.module.css
  src/asset/mdi_pencil.svg
  src/components/Modal.tsx
  src/styles/Modal.module.css
Labels: fix

#64 !HOTFIX 소셜로그인 데이터베이스에 저장 안되던 현상 수정
  src/app/api/auth/[...nextauth]/route.ts
  src/app/profile/[id]/_components/ProfileModifyForm.tsx
  src/app/profile/[id]/_components/Sidebar.tsx
  src/app/profile/[id]/_styles/Community.module.css
  src/app/profile/[id]/_styles/Profile.module.css
  src/app/profile/[id]/_styles/ProfileModifyForm.module.css
  src/app/profile/[id]/_styles/ReservationDetail.module.css
  src/app/profile/[id]/_styles/Sidebar.module.css
  src/app/profile/[id]/community/page.tsx
  src/app/profile/[id]/page.tsx
Labels: fix

#65 Feat/camp 검색페이지 시설필터기능추가
  next.config.js
  src/app/_components/PopularCamp.tsx
  src/app/_lib/facility.ts
  src/app/api/camp/search/route.ts
  src/app/api/like.ts
  src/app/camp/_components/CampFilter.tsx
  src/app/camp/_components/CampList.tsx
  src/app/camp/_components/FacilityFilter.tsx
  src/app/camp/_components/PageController.tsx
  src/app/camp/page.tsx
  src/app/camp/search/_components/SearchPageController.tsx
  src/app/camp/search/page.tsx
  src/types/campList.ts
Labels: 기능

#70 Feat/community 커뮤니티U
  src/app/community/[id]/create/page.tsx
  src/app/community/_components/CommuEditModal.tsx
  src/app/community/_components/CommuUsers.tsx
  src/app/community/_styles/Commu.module.css
  src/app/community/_styles/CommuCreate.module.css
  src/app/community/_styles/CommuEditModal.module.css
  src/app/community/_styles/CommuHashTags.module.css
  src/app/community/_svg/CommuPicSvg.tsx
  src/app/community/page.tsx
  src/styles/globals.css
Labels: 기능

#72 Feat/camp camp 페이지 rpc적용
  package.json
  src/app/_components/PopularCamp.tsx
  src/app/api/camp/search/route.ts
  src/app/camp/_components/CampFilter.tsx
  src/app/camp/_components/CampList.tsx
  src/app/camp/_components/FacilityFilter.tsx
  src/app/camp/_components/Hashtag.tsx
  src/app/camp/page.tsx
  src/app/camp/search/_components/SearchView.tsx
  src/app/camp/search/page.tsx
  src/app/community/_components/CommuEditModal.tsx
  src/app/community/_components/CommuUsers.tsx
  src/types/campList.ts
  src/types/supabase.ts
  yarn.lock
Labels: 기능

#73 Feat/camp search페이지 rpc 적용
  src/app/_components/RegionCarousel.tsx
  src/app/api/camp/search/route.ts
  src/app/camp/_components/CampList.tsx
  src/app/camp/_components/FacilityFilter.tsx
  src/app/camp/_components/Photo.tsx
  src/app/camp/_styles/FacilityFilter.module.css
  src/app/camp/page.tsx
  src/app/camp/search/_components/SearchView.tsx
  src/app/camp/search/page.tsx
  src/types/campList.ts
  src/types/supabase.ts
Labels: 기능

#75 Feat/main 메인페이지 커뮤니티 캐러셀
  src/app/_components/CommunityCarousel.module.css
  src/app/_components/CommunityCarousel.tsx
  src/app/_components/PopularCommunity.tsx
  src/app/_components/RightArrowSvg.tsx
  src/app/_styles/PopularCommunity.module.css
  src/asset/icon_arrow_right.svg
  src/asset/region/강원.jpg
  src/asset/region/경기.jpg
  src/asset/region/경남.jpg
  src/asset/region/경북.jpg
  src/asset/region/광주.jpg
  src/asset/region/대구.jpg
  src/asset/region/대전.jpg
  src/asset/region/부산.jpg
  src/asset/region/서울.jpg
  src/asset/region/울산.jpg
  src/asset/region/인천.jpg
  src/asset/region/전남.jpg
  src/asset/region/전북.jpg
  src/asset/region/제주.jpg
  src/asset/region/충남.jpg
  src/asset/region/충북.jpg
  src/types/supabase.ts
Labels: 기능, UI

#76 Feat/header searchBar 디테일기능 및 해시태그 검색
  src/app/_components/Header.tsx
  src/app/_components/RightArrowSvg.tsx
  src/app/_components/SearchBar.tsx
  src/app/_styles/Header.module.css
  src/app/camp/_components/CampFilter.tsx
  src/app/camp/_components/Hashtag.tsx
  src/app/camp/_lib/formattedDate.ts
  src/asset/icon_arrow_right.svg
  src/components/CommunitySvg.tsx
Labels: 기능, Style

#77 Style/search 정렬버튼, 필터 css
  src/app/_components/CommunityCarousel.tsx
  src/app/_styles/CommunityCarousel.module.css
  src/app/camp/_components/CampFilter.tsx
  src/app/camp/_components/Hashtag.tsx
  src/app/camp/_components/PageController.tsx
  src/app/camp/_styles/Camp.module.css
  src/app/camp/_styles/CampFilter.module.css
  src/app/camp/_styles/CampList.module.css
  src/app/camp/page.tsx
  src/app/camp/search/_components/SearchView.tsx
  src/app/camp/search/page.tsx
  src/asset/icon_down.svg
  src/components/Drop.tsx
Labels: Style

#78 Feat/manage company 업체회원 페이지 CSS
  src/app/company/[id]/_styles/CompanyHeader.module.css
  src/app/company/[id]/_styles/CompanyLayout.module.css
  src/app/company/[id]/layout.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/AddForm.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/CampPicture.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/CheckInOut.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Facility.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Hashtag.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Layout.tsx
  src/app/company/[id]/manage_camp/add_camp/_styles/CampForm.module.css
  src/app/company/[id]/manage_camp/add_camp/page.tsx
  src/app/company/[id]/manage_camp/added_camp/_styles/Camp.module.css
  src/app/company/[id]/manage_camp/added_camp/page.tsx
  src/asset/addImgBtn.png
  src/asset/ico_removePicBtn.png
  src/asset/ico_right_arrow_gray.png
  src/asset/ico_small_remove_btn.png
  src/asset/icon-preview.png
Labels: UI, Style

#81 Feat/reservation form
  src/app/_components/AlertModal.tsx
  src/app/_components/ConfirmModal.tsx
  src/app/_styles/ConfirmModal.module.css
  src/app/camp/detail/[id]/_components/Calendar.tsx
  src/app/camp/detail/[id]/_components/CompleteModal.tsx
  src/app/camp/detail/[id]/_components/ConfirmModal.tsx
  src/app/camp/detail/[id]/_components/DetailCampZone.tsx
  src/app/camp/detail/[id]/_components/ReservationForm.tsx
  src/app/camp/detail/[id]/_components/ReservationModal.tsx
  src/app/camp/detail/[id]/_styles/Button.module.css
  src/app/camp/detail/[id]/_styles/CompleteModal.module.css
  src/app/camp/detail/[id]/_styles/ConfirmModal.module.css
  src/app/camp/detail/[id]/_styles/ReservationForm.module.css
  src/app/camp/detail/[id]/_styles/ReservationModal.module.css
  src/app/camp/detail/[id]/_svg/KakaoPaySvg.tsx
  src/app/camp/detail/[id]/reservation/page.tsx
  src/app/company/[id]/manage_reservation/_components/Reservation.tsx
  src/app/profile/[id]/_components/ReservationDetailModal.tsx
  src/asset/camping_illust.jpg
Labels: 기능, UI, Style

#83 [Feat/profile] 프로필 페이지 디자인 수정 및 리뷰 모달
  src/app/api/camp/review/[id]/route.ts
  src/app/api/profile/[id]/route.ts
  src/app/profile/[id]/_components/Profile.tsx
  src/app/profile/[id]/_components/ProfileModifyForm.tsx
  src/app/profile/[id]/_components/Rating.tsx
  src/app/profile/[id]/_components/ReservationList.tsx
  src/app/profile/[id]/_components/ReviewModal.tsx
  src/app/profile/[id]/_components/Sidebar.tsx
  src/app/profile/[id]/_lib/getUserReservation.ts
  src/app/profile/[id]/_styles/Content.module.css
  src/app/profile/[id]/_styles/Profile.module.css
  src/app/profile/[id]/_styles/ProfileModifyForm.module.css
  src/app/profile/[id]/_styles/Rating.module.css
  src/app/profile/[id]/_styles/ReservationDetailModal.module.css
  src/app/profile/[id]/_styles/ReviewModal.module.css
  src/app/profile/[id]/_styles/Sidebar.module.css
  src/app/profile/[id]/layout.tsx
  src/asset/icon_camp.svg
  src/asset/icon_community.svg
  src/asset/icon_profile_setting.svg
  src/components/Modal.tsx
  src/types/reservation.ts
Labels: fix, UI, Style

#84 !HOTFIX 헤더 프로필 변경 이미지 적용
  src/app/_components/Header.tsx
Labels: fix

#85 [!HOTFIX] 미들웨어 수정
  src/app/api/auth/[...nextauth]/route.ts
  src/middleware.ts
Labels: fix

#86 Feat/manage company 캠핑장 등록 페이지, 캠핑존 등록 모달, 캠핑장 수정 페이지 CSS
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/_components/CampAreaModal.tsx
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/_styles/CampAreaForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/page.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/CampPicture.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/CheckInOut.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/Facility.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/Hashtag.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/Layout.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_styles/CampForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/page.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/AddForm.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/CampPicture.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Hashtag.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Layout.tsx
  src/app/company/[id]/manage_camp/add_camp/_styles/CampForm.module.css
  src/app/company/[id]/manage_camp/added_camp/_styles/Camp.module.css
  src/app/company/[id]/manage_camp/added_camp/page.tsx
  src/app/company/[id]/manage_company_user_info/page.tsx
  src/asset/ico_cancel_btn.png
Labels: fix, UI, Style

#87 Feat/community 커뮤니티CSS
  src/app/community/[id]/create/page.tsx
  src/app/community/_components/CommuBtns.tsx
  src/app/community/_components/CommuComment.tsx
  src/app/community/_components/CommuDetailModal.tsx
  src/app/community/_components/CommuEditModal.tsx
  src/app/community/_components/CommuEditPic.tsx
  src/app/community/_components/CommuPhotos.tsx
  src/app/community/_components/CommuUsers.tsx
  src/app/community/_styles/CommuDetailModal.module.css
  src/app/community/_styles/CommuEditModal.module.css
  src/app/community/_styles/CommuPhotos.module.css
  src/app/community/_styles/CommuUser.module.css
  src/app/community/_svg/CommentSvg.tsx
  src/app/community/_svg/DeleteSvg.tsx
  src/app/community/page.tsx
  src/components/CarouselNextArrow.tsx
  src/components/CarouselPrevArrow.tsx
Labels: UI, Style

#89 Feat/mypage-cancel 마이페이지 예약 취소
  src/app/profile/[id]/_components/CompleteModal.tsx
  src/app/profile/[id]/_components/ConfirmModal.tsx
  src/app/profile/[id]/_components/ReservationDetail.tsx
  src/app/profile/[id]/_components/ReservationDetailModal.tsx
  src/app/profile/[id]/_components/ReservationList.tsx
  src/app/profile/[id]/_lib/deleteUserReservation.ts
  src/app/profile/[id]/_styles/CompleteModal.module.css
  src/app/profile/[id]/_styles/ConfirmModal.module.css
  src/app/profile/[id]/_styles/ReservationDetail.module.css
  src/app/profile/[id]/_styles/ReservationDetailModal.module.css
  src/app/profile/[id]/_styles/ReservationList.module.css
Labels: 기능, UI, Style

#90 feat: 캠핑장 찜 목록 기능 (#24)
  package.json
  src/app/_components/CampProvider.tsx
  src/app/api/profile/[id]/like/camp/route.ts
  src/app/profile/[id]/_components/BookmarkCamp.tsx
  src/app/profile/[id]/_components/Profile.tsx
  src/app/profile/[id]/_lib/getUserLikeCamp.ts
  src/types/profile.ts
  yarn.lock
Labels: 기능, fix

#91 fix: 미들웨어 수정 (#4)
  src/middleware.ts
Labels: fix

#93 Fix/mypage-cancel 예약 모달창 닫기 버튼 추가
  src/app/camp/detail/[id]/_components/ReservationModal.tsx
  src/app/camp/detail/[id]/_styles/ReservationModal.module.css
Labels: fix

#96 Feat/pagination camp, search 페이지 페이지네이션 추가
  src/app/_components/CampCarousel.tsx
  src/app/_components/CampCarouselNextArrow.tsx
  src/app/_components/CampCarouselPrevArrow.tsx
  src/app/_components/Header.tsx
  src/app/_components/PopularCommunity.tsx
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/camp/review/[id]/route.ts
  src/app/api/camp/search/route.ts
  src/app/camp/_components/FacilityFilter.tsx
  src/app/camp/_components/PageController.tsx
  src/app/camp/_components/Pagination.tsx
  src/app/camp/_styles/PageController.module.css
  src/app/camp/_styles/Pagination.module.css
  src/app/camp/detail/[id]/_components/Calendar.tsx
  src/app/camp/page.tsx
  src/app/camp/search/_components/SearchPageController.tsx
  src/app/camp/search/_components/SearchView.tsx
  src/app/camp/search/_lib/paginateCamp.ts
  src/app/camp/search/page.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/Layout.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Layout.tsx
  src/app/company/[id]/manage_company_user_info/page.tsx
  src/app/profile/[id]/_components/ReviewModal.tsx
Labels: 기능

#100 Feat/profile 찜 캠핑장 기능
  src/app/api/profile/[id]/like/camp/route.ts
  src/app/profile/[id]/_components/BookmarkCamp.tsx
  src/app/profile/[id]/_components/BookmarkCampContent.tsx
  src/app/profile/[id]/_lib/getUserLikeCamp.ts
  src/app/profile/[id]/_styles/BookmarkCamp.module.css
  src/app/profile/[id]/_styles/BookmarkCampContent.module.css
  src/app/profile/[id]/_styles/MypageLayout.module.css
  src/app/profile/[id]/layout.tsx
  src/components/AddressSvg.tsx
  src/components/Card.tsx
  src/middleware.ts
  src/styles/Card.module.css
  src/types/profile.ts
Labels: 기능, UI

#104 Feat/manage company CSS 적용 및 기능 수정
  src/app/company/[id]/_components/CompanyHeader.tsx
  src/app/company/[id]/_styles/CompanyHeader.module.css
  src/app/company/[id]/layout.tsx
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/_components/CampAreaModal.tsx
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/_styles/CampAreaForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/page.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/AddressModal.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/CheckInOut.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/Hashtag.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/SearchAddress.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_styles/SearchAddress.module.css
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/page.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/AddForm.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/CheckInOut.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Hashtag.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/SearchAddress.tsx
  src/app/company/[id]/manage_camp/added_camp/page.tsx
  src/app/company/[id]/manage_company_user_info/_styles/ManageCompanyUserInfo.module.css
  src/app/company/[id]/manage_company_user_info/page.tsx
  src/asset/ico_edit_company_user_name.png
  src/asset/ico_manage_company.png
  src/asset/ico_manage_company_active.png
  src/asset/ico_managecamp.png
  src/asset/ico_managecamp_active.png
  src/asset/ico_reservation.png
  src/asset/ico_reservation_active.png
Labels: fix, UI, Style

#106 Feat/header 헤더 수정
  src/app/_components/Calendar.tsx
  src/app/_components/Header.tsx
  src/app/_components/SearchBar.tsx
  src/app/_components/a.tsx
  src/app/_styles/Calendar.module.css
  src/app/_styles/Header.module.css
  src/app/_styles/SearchBar.module.css
  src/app/layout.tsx
  src/asset/Calendar.svg
Labels: fix, Style

#107 Feat/profile 모달 수정
  src/app/_components/Header.tsx
  src/app/_components/a.tsx
  src/app/profile/[id]/_components/BookmarkCamp.tsx
  src/app/profile/[id]/_components/BookmarkCampContent.tsx
  src/app/profile/[id]/_components/BookmarkPost.tsx
  src/app/profile/[id]/_components/BookmarkPostContent.tsx
  src/app/profile/[id]/_components/Profile.tsx
  src/app/profile/[id]/_components/ProfileModifyForm.tsx
  src/app/profile/[id]/_lib/getUserData.ts
  src/app/profile/[id]/_lib/getUserLikeCamp.ts
  src/app/profile/[id]/_lib/getUserLikePost.ts
  src/app/profile/[id]/_lib/profile.ts
  src/app/profile/[id]/_styles/BookmarkCampContent.module.css
  src/app/profile/[id]/_styles/BookmarkPostContent.module.css
  src/middleware.ts
  src/styles/Modal.module.css
Labels: fix, UI
