Repository h0ngwon/Camperspot, pull requests merged in 2024-02, with the labels that each got.

#109 Feat/community 커뮤니티수정
  src/app/community/_components/CommuCreateModal.tsx
  src/app/community/_components/CommuEditModal.tsx
  src/app/community/_components/CommuLikeBtn.tsx
  src/app/community/_components/CommuPic.tsx
  src/app/community/_styles/CommuPhotos.module.css
  src/app/community/_styles/CommuUser.module.css
  src/app/community/page.tsx
  src/app/company/[id]/manage_camp/added_camp/page.tsx
Labels: fix

#110 Fix/reservation 예약 현황 페이지 수정
  src/app/api/company/[id]/reservation/route.ts
  src/app/camp/detail/[id]/_components/DetailCampZone.tsx
  src/app/company/[id]/_lib/getCompanyUserReservation.ts
  src/app/company/[id]/_svg/ResrevationSearchSvg.tsx
  src/app/company/[id]/manage_reservation/_components/Calendar.tsx
  src/app/company/[id]/manage_reservation/_components/NothingReservation.tsx
  src/app/company/[id]/manage_reservation/_components/Reservation.tsx
  src/app/company/[id]/manage_reservation/_components/ReservationList.tsx
  src/app/company/[id]/manage_reservation/_lib/getEndDate.ts
  src/app/company/[id]/manage_reservation/_styles/Calendar.module.css
  src/app/company/[id]/manage_reservation/_styles/NothingReservation.module.css
  src/app/company/[id]/manage_reservation/_styles/Reservation.module.css
  src/app/company/[id]/manage_reservation/_styles/ReservationList.module.css
  src/app/company/[id]/manage_reservation/page.tsx
  src/types/reservation.ts
Labels: 기능, UI, Style

#111 Feat/community 커뮤니티U 이미지오류수정
  src/app/community/_components/CommuEditModal.tsx
Labels: bug, fix

#112 Feat/manage camp 페이지 버튼 되돌려진거 다시 수정
  src/app/company/[id]/manage_camp/added_camp/page.tsx
Labels: fix

#113 Feat/profile 별점 리뷰 기능
  src/app/profile/[id]/_components/Rating.tsx
  src/app/profile/[id]/_components/ReviewModal.tsx
  src/app/profile/[id]/_lib/review.ts
  src/app/profile/[id]/_styles/Rating.module.css
  src/app/profile/[id]/_styles/ReviewModal.module.css
Labels: 기능, fix

#115 Fix/camp camp 페이지 및 캐러셀 버튼 수정
  src/app/_components/CampCarousel.tsx
  src/app/_components/CampCarouselNextArrow.tsx
  src/app/_components/CampCarouselPrevArrow.tsx
  src/app/_components/Carousel.tsx
  src/app/_components/Header.tsx
  src/app/_components/PopularCamp.tsx
  src/app/_components/PopularCommunity.tsx
  src/app/_components/ProfileDivider.tsx
  src/app/_components/Providers.tsx
  src/app/_components/QueryProvider.tsx
  src/app/_components/RegionCarousel.tsx
  src/app/_styles/CampCard.module.css
  src/app/_styles/PopularCommunity.module.css
  src/app/_styles/SearchBar.module.css
  src/app/api/camp/search/route.ts
  src/app/camp/_components/CampFilter.tsx
  src/app/camp/_components/CampList.tsx
  src/app/camp/_components/PageController.tsx
  src/app/camp/_components/Photo.tsx
  src/app/camp/_lib/getPageControllerProps.ts
  src/app/camp/page.tsx
  src/app/camp/search/page.tsx
  src/app/community/_components/CommuEditModal.tsx
  src/app/community/_components/CommuPhotos.tsx
  src/app/layout.tsx
  src/components/NextArrow.tsx
  src/components/PrevArrow.tsx
  src/styles/CarouselBtn.module.css
  src/types/supabase.ts
Labels: fix, Style

#117 Feat/community Like버튼 오류 수정
  src/app/camp/detail/[id]/_components/DetailLikeBtn.tsx
  src/app/community/_components/CommuLikeBtn.tsx
Labels: fix

#118 Feat/manage company 캠핑존 삭제시 예약자 있으면 삭제 막기
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/_styles/CampAreaForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/page.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/page.tsx
Labels: 기능, Style

#119 Feat/profile 리뷰 등록 기능
  src/app/api/camp/review/[id]/route.ts
  src/app/api/camp/review/route.ts
  src/app/camp/detail/[id]/_components/DetailAvg.tsx
  src/app/camp/detail/[id]/_components/DetailCampZone.tsx
  src/app/camp/detail/[id]/_components/DetailReviews.tsx
  src/app/profile/[id]/_components/ReviewModal.tsx
  src/app/profile/[id]/_lib/review.ts
  src/types/review.ts
  src/types/supabase.ts
  src/types/supabaseSchema.ts
Labels: 기능

#121 Fix/profile 리뷰 기능 수정 (#24)
  src/app/api/camp/[id]/review/route.ts
  src/app/api/camp/review/route.ts
  src/app/profile/[id]/_components/ReviewModal.tsx
  src/app/profile/[id]/_lib/review.ts
Labels: fix

#122 Fix/ut UT 반영
  src/app/_components/People.tsx
  src/app/_components/SearchBar.tsx
  src/app/camp/_styles/Camp.module.css
  src/app/camp/page.tsx
  src/app/camp/search/_components/SearchReasultSvg.tsx
  src/app/camp/search/_components/SearchView.tsx
  src/asset/fluent-emoji-flat_camping.svg
Labels: fix

#124 Fix/rpc rpc수정
  src/app/_components/CampCard.tsx
  src/app/_components/CampCarousel.tsx
  src/app/_components/PopularCamp.tsx
  src/app/api/camp/search/route.ts
  src/app/camp/_components/CampFilter.tsx
  src/app/camp/_components/CampList.tsx
  src/app/camp/_components/FacilityFilter.tsx
  src/app/camp/detail/[id]/_components/DetailCampZone.tsx
  src/app/camp/detail/[id]/_components/DetailLikeBtn.tsx
  src/app/camp/page.tsx
  src/app/camp/search/page.tsx
  src/app/community/_components/CommuLikeBtn.tsx
  src/app/community/page.tsx
  src/types/campList.ts
  src/types/supabase.ts
Labels: fix

#125 Feat/manage company update_camp 페이지 캠핑장 이미지 바로 반영
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/page.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/AddForm.tsx
  src/app/company/[id]/manage_camp/added_camp/page.tsx
Labels: fix

#127 Feat/profile 로딩페이지 및 404 페이지 추가
  src/app/layout.tsx
  src/app/loading.tsx
  src/app/not-found.tsx
  src/asset/404.gif
  src/asset/loader.gif
  src/styles/Loading.module.css
  src/styles/NotFound.module.css
Labels: 디자인 🎨

#128 feat 커뮤니티 댓글 등록 및 확인
  src/app/community/_components/CommuComment.tsx
  src/app/community/_components/CommuComments.tsx
  src/app/community/_components/CommuCreateComment.tsx
  src/app/community/_components/CommuDetailModal.tsx
Labels: 기능 🔧

#129 Fix/reservation 예약 현황 캠핑장 필터 기능 추가
  src/app/camp/detail/[id]/_components/CompleteModal.tsx
  src/app/camp/detail/[id]/_components/DetailCampZone.tsx
  src/app/camp/detail/[id]/_components/ReservationForm.tsx
  src/app/company/[id]/_svg/ExclamationMarkSvg.tsx
  src/app/company/[id]/manage_reservation/_components/CampFilter.tsx
  src/app/company/[id]/manage_reservation/_components/Reservation.tsx
  src/app/company/[id]/manage_reservation/_components/ReservationList.tsx
  src/app/company/[id]/manage_reservation/_components/TotalReservationList.tsx
  src/app/company/[id]/manage_reservation/_styles/CampFilter.module.css
  src/app/company/[id]/manage_reservation/_styles/Reservation.module.css
  src/app/company/[id]/manage_reservation/_styles/TotalReservationList.module.css
  src/components/Drop.tsx
Labels: 기능수정 🛠, 디자인 🎨, 오류 수정 ❗

#130 Feat/manage company useQuery 문으로 리팩토링
  src/app/company/[id]/manage_company_user_info/page.tsx
Labels: 기능수정 🛠

#131 feat: 리뷰 삭제 기능 (#24)
  next.config.js
  src/app/api/profile/[id]/review/route.ts
  src/app/profile/[id]/_components/ReviewConfirmModal.tsx
  src/app/profile/[id]/_components/ReviewModal.tsx
  src/app/profile/[id]/_components/Star.tsx
  src/app/profile/[id]/_components/UserReview.tsx
  src/app/profile/[id]/_lib/review.ts
  src/app/profile/[id]/_styles/ReviewConfirmModal.module.css
  src/app/profile/[id]/_styles/Star.module.css
  src/app/profile/[id]/_styles/UserReview.module.css
  src/app/profile/[id]/reservation/page.tsx
  src/styles/globals.css
  src/types/review.ts
Labels: 기능 🔧, 디자인 🎨

#133 Style/footer footer 제작
  src/app/_components/Calendar.tsx
  src/app/_components/Footer.tsx
  src/app/_components/Main.tsx
  src/app/_styles/Footer.module.css
  src/app/camp/_components/CampList.tsx
  src/app/camp/_styles/Camp.module.css
  src/app/camp/_styles/CampList.module.css
  src/app/camp/detail/[id]/_components/DetailLikeBtn.tsx
  src/app/camp/detail/[id]/page.tsx
  src/app/camp/page.tsx
  src/app/layout.tsx
Labels: 디자인 🎨

#134 Feat/manage company 캠핑장 등록, 수정 페이지
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/page.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/CampPicture.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/Layout.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_styles/CampForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/page.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/AddForm.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/CampPicture.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Layout.tsx
  src/app/company/[id]/manage_camp/add_camp/_styles/CampForm.module.css
  src/app/company/[id]/manage_camp/added_camp/page.tsx
Labels: 기능수정 🛠

#135 Fix/reservation
  src/app/company/[id]/_svg/InputEraserSvg.tsx
  src/app/company/[id]/_svg/QuestionMarkSvg.tsx
  src/app/company/[id]/manage_reservation/_components/Calendar.tsx
  src/app/company/[id]/manage_reservation/_components/CampFilter.tsx
  src/app/company/[id]/manage_reservation/_components/Reservation.tsx
  src/app/company/[id]/manage_reservation/_components/Tooltip.tsx
  src/app/company/[id]/manage_reservation/_components/TotalReservationList.tsx
  src/app/company/[id]/manage_reservation/_styles/Calendar.module.css
  src/app/company/[id]/manage_reservation/_styles/NothingReservation.module.css
  src/app/company/[id]/manage_reservation/_styles/Tooltip.module.css
  src/app/company/[id]/manage_reservation/_styles/TotalReservationList.module.css
Labels: 기능수정 🛠, 디자인 🎨

#136 style 커뮤댓글css
  src/app/community/_components/CommuComment.tsx
  src/app/community/_components/CommuComments.tsx
  src/app/community/_components/CommuDetailModal.tsx
  src/app/community/_components/CommuPhotos.tsx
  src/app/community/_styles/CommuDetailModal.module.css
  src/app/community/_styles/CommuPhotos.module.css
Labels: 디자인 🎨

#137 fix: 마이페이지 커뮤니티 수정 (#24)
  src/app/api/profile/[id]/community/like/route.ts
  src/app/api/profile/[id]/community/user/post/route.ts
  src/app/profile/[id]/_components/BookmarkPost.tsx
  src/app/profile/[id]/_components/BookmarkPostContent.tsx
  src/app/profile/[id]/_components/MyPost.tsx
  src/app/profile/[id]/_components/MyPostContent.tsx
  src/app/profile/[id]/_lib/profile.ts
  src/app/profile/[id]/_styles/MyPost.module.css
  src/app/profile/[id]/_styles/MyPostContent.module.css
  src/app/profile/[id]/community/page.tsx
  src/asset/icon_comment.svg
  src/asset/icon_like.svg
  src/components/Card.tsx
  src/styles/Card.module.css
  src/types/profile.ts
Labels: 기능수정 🛠, 디자인 🎨

#139 style 커뮤댓글
  src/app/camp/detail/[id]/_styles/Like.module.css
  src/app/community/_components/CommuBtns.tsx
  src/app/community/_components/CommuComments.tsx
  src/app/community/_components/CommuCreateComment.tsx
  src/app/community/_components/CommuLikeBtn.tsx
  src/app/community/_styles/Commu.module.css
  src/app/community/_styles/CommuBtn.module.css
  src/app/community/_styles/CommuDetailModal.module.css
  src/app/community/_styles/CommuHashTags.module.css
  src/app/community/page.tsx
Labels: 디자인 🎨

#140 Fix/profile 리뷰 삭제 모달창 수정
  src/app/profile/[id]/_components/ReviewConfirmModal.tsx
  src/app/profile/[id]/_components/UserReview.tsx
Labels: 기능수정 🛠

#141 fix: 로딩페이지 react-query 및 ssr 페이지에 적용
  src/app/camp/detail/[id]/_components/DetailLikeBtn.tsx
  src/app/camp/detail/[id]/page.tsx
  src/app/camp/page.tsx
  src/app/community/_components/CommuComments.tsx
  src/app/community/_components/CommuCreateComment.tsx
  src/app/community/_components/CommuLikeBtn.tsx
  src/app/community/page.tsx
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/page.tsx
  src/app/company/[id]/manage_camp/added_camp/page.tsx
  src/app/company/[id]/manage_reservation/_components/ReservationList.tsx
  src/app/company/[id]/manage_reservation/_components/TotalReservationList.tsx
  src/app/layout.tsx
  src/app/profile/[id]/_components/BookmarkCamp.tsx
  src/app/profile/[id]/_components/MyPost.tsx
  src/app/profile/[id]/_components/Profile.tsx
  src/app/profile/[id]/_components/ProfileModifyForm.tsx
  src/app/profile/[id]/_components/ReservationDetail.tsx
  src/app/profile/[id]/_components/Sidebar.tsx
  src/app/profile/[id]/layout.tsx
  src/styles/Loading.module.css
Labels: 디자인 🎨

#143 Feat/commu 상세페이지css
  src/app/camp/detail/[id]/_components/DetailAvg.tsx
  src/app/camp/detail/[id]/_components/DetailLikeBtn.tsx
  src/app/camp/detail/[id]/_components/DetailReviews.tsx
  src/app/camp/detail/[id]/_styles/Detail.module.css
  src/app/camp/detail/[id]/_styles/DetailAddress.module.css
  src/app/camp/detail/[id]/_styles/DetailAvg.module.css
  src/app/camp/detail/[id]/_styles/DetailHashtag.module.css
  src/app/camp/detail/[id]/_styles/DetailReview.module.css
  src/app/camp/detail/[id]/_styles/Like.module.css
  src/app/camp/detail/[id]/_svg/HeartSvg.tsx
  src/app/camp/detail/[id]/_svg/Star.tsx
  src/app/camp/detail/[id]/page.tsx
  src/app/community/_components/CommuComments.tsx
  src/app/community/_styles/CommuDetailModal.module.css
Labels: 디자인 🎨

#144 Style/main 헤더 ui 수정
  src/app/_Svg/Company.tsx
  src/app/_Svg/LogoSvg.tsx
  src/app/_Svg/MinusSvg.tsx
  src/app/_Svg/PlusSvg.tsx
  src/app/_components/CampCarousel.tsx
  src/app/_components/Carousel.tsx
  src/app/_components/Header.tsx
  src/app/_components/People.tsx
  src/app/_components/PeopleCount.tsx
  src/app/_components/ProfileDivider.tsx
  src/app/_components/ProfileDropDown.tsx
  src/app/_components/SearchBar.tsx
  src/app/_styles/Calendar.module.css
  src/app/_styles/Header.module.css
  src/app/_styles/PeopleCount.module.css
  src/app/_styles/ProfileDiveder.module.css
  src/app/_styles/ProfileDropDown.module.css
  src/app/_styles/SearchBar.module.css
  src/app/auth/signin/_styles/SigninPage.module.css
  src/app/auth/signin/page.tsx
  src/app/auth/signup/_styles/SignupPage.module.css
  src/app/auth/signup/page.tsx
  src/app/camp/_components/CampFilter.tsx
  src/app/camp/page.tsx
  src/app/community/_components/CommuPhotos.tsx
  src/app/community/_svg/CommentSvg.tsx
  src/app/community/_svg/CreateSvg.tsx
  src/app/community/_svg/DeleteSvg.tsx
  src/asset/logo.png
  src/asset/logo2.png
  src/styles/NotFound.module.css
Labels: 디자인 🎨

#145 Fix/reservation 마이페이지 예약현황 UI 수정
  src/app/camp/detail/[id]/_components/CompleteModal.tsx
  src/app/camp/detail/[id]/_components/ConfirmModal.tsx
  src/app/camp/detail/[id]/_components/ReservationForm.tsx
  src/app/camp/detail/[id]/_components/ReservationModal.tsx
  src/app/camp/detail/[id]/_styles/CompleteModal.module.css
  src/app/camp/detail/[id]/_styles/ConfirmModal.module.css
  src/app/camp/detail/[id]/_styles/ReservationForm.module.css
  src/app/camp/detail/[id]/_styles/ReservationModal.module.css
  src/app/camp/detail/[id]/_svg/CheckSvg.tsx
  src/app/company/[id]/manage_reservation/_components/TotalReservationList.tsx
  src/app/company/[id]/manage_reservation/_styles/Calendar.module.css
  src/app/profile/[id]/_components/ConfirmModal.tsx
  src/app/profile/[id]/_components/NothingReservation.tsx
  src/app/profile/[id]/_components/ReservationDetail.tsx
  src/app/profile/[id]/_components/ReservationDetailModal.tsx
  src/app/profile/[id]/_components/ReservationList.tsx
  src/app/profile/[id]/_styles/CompleteModal.module.css
  src/app/profile/[id]/_styles/ConfirmModal.module.css
  src/app/profile/[id]/_styles/NothingReservation.module.css
  src/app/profile/[id]/_styles/ReservationDetail.module.css
  src/app/profile/[id]/_styles/ReservationDetailModal.module.css
  src/app/profile/[id]/_styles/ReservationList.module.css
  src/app/profile/[id]/_svg/CoordiateSvg.tsx
  src/components/ReservationArrowSvg.tsx
  src/styles/globals.css
Labels: 기능수정 🛠, 디자인 🎨

#147 Feat/manage company 캠핑장 삭제 기능 추가, 캠핑존 삭제 오류 해결
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/page.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_styles/CampForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/page.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/AddForm.tsx
  src/app/company/[id]/manage_company_user_info/page.tsx
Labels: 기능 🔧, 오류 수정 ❗

#149 Docs README.md 수정
  README.md
  package.json
  public/img/검색.png
  public/img/검색2.png
  public/img/리뷰.png
  public/img/예약1.png
  public/img/예약2.png
  public/img/예약3.png
  public/img/운영1.png
  public/img/운영2.png
  public/img/운영3.png
  public/img/운영4.png
  public/img/캠퍼스팟 유저테스트용 홍보 카드-1.png
  public/img/캠퍼스팟 유저테스트용 홍보 카드-2.png
  public/img/커뮤니티.png
  public/img/커뮤니티2.png
  src/app/api/auth/[...nextauth]/route.ts
  src/asset/logo.svg
  src/middleware.ts
  src/types/next-auth.d.ts
  yarn.lock
Labels: 기타

#150 Docs README.md 수정
  README.md
Labels: 기타

#154 Fix/optimization build warning 수정
  src/app/_Svg/MinusSvg.tsx
  src/app/_Svg/PlusSvg.tsx
  src/app/_Svg/ResetSvg.tsx
  src/app/_components/AuthSession.tsx
  src/app/_components/Calendar.tsx
  src/app/_components/People.tsx
  src/app/_components/PeopleCount.tsx
  src/app/_components/PopularCamp.tsx
  src/app/_components/ProfileDivider.tsx
  src/app/_components/ProfileDropDown.tsx
  src/app/_components/SearchBar.tsx
  src/app/_styles/Calendar.module.css
  src/app/api/camp/route.ts
  src/app/camp/_components/FacilityFilter.tsx
  src/app/camp/_components/PageController.tsx
  src/app/camp/_lib/getPageControllerProps.ts
  src/app/camp/detail/[id]/_components/Calendar.tsx
  src/app/camp/detail/[id]/_components/KakaoMap.tsx
  src/app/camp/detail/[id]/_components/ReservationModal.tsx
  src/app/camp/search/_lib/paginateCamp.ts
  src/app/community/_components/CommuDragAndDrop.tsx
  src/app/company/[id]/_svg/InputEraserSvg.tsx
  src/app/company/[id]/manage_camp/[camp_id]/manage_camp_area/page.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_components/Facility.tsx
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/page.tsx
  src/app/company/[id]/manage_camp/add_camp/_components/Facility.tsx
Labels: 리팩토링 ⚙, 오류 수정 ❗

#155 style/main css 수정
  src/app/_components/RegionCarousel.tsx
  src/app/_styles/CampCard.module.css
  src/app/_styles/Header.module.css
  src/app/_styles/PopularCommunity.module.css
  src/app/_styles/RegionFiltter.module.css
  src/app/camp/_components/CampList.tsx
Labels: 디자인 🎨

#156 Refactor: React Query 코드 Custom Hook으로 분리
  src/app/profile/[id]/_components/BookmarkCamp.tsx
  src/app/profile/[id]/_components/MyPost.tsx
  src/app/profile/[id]/_components/Profile.tsx
  src/app/profile/[id]/_components/ProfileModifyForm.tsx
  src/app/profile/[id]/_components/ReviewConfirmModal.tsx
  src/app/profile/[id]/_components/UserReview.tsx
  src/app/profile/[id]/_lib/modifyUserData.ts
  src/app/profile/[id]/_lib/profile.ts
  src/hooks/useLikeCampQuery.ts
  src/hooks/useMyPostQuery.ts
  src/hooks/useProfileQuery.ts
  src/hooks/useReviewQuery.ts
Labels: 리팩토링 ⚙

#157 Feat/manage company 전화번호 유효성 검사 오류 수정
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_lib/validation.ts
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/_styles/CampForm.module.css
  src/app/company/[id]/manage_camp/[camp_id]/update_camp/page.tsx
Labels: 기능수정 🛠, 오류 수정 ❗

#158 style/main 헤더 메인 수정
  src/app/_components/CommunityCarousel.tsx
  src/app/_components/SearchBar.tsx
  src/app/_styles/PopularCommunity.module.css
Labels: 디자인 🎨

#159 Fix/reservation 예약 관련 스타일 수정
  src/app/camp/detail/[id]/_styles/CompleteModal.module.css
  src/app/company/[id]/_styles/CompanyLayout.module.css
  src/app/company/[id]/manage_reservation/_components/CampFilter.tsx
  src/app/company/[id]/manage_reservation/_components/Reservation.tsx
  src/app/company/[id]/manage_reservation/_components/TotalReservationList.tsx
  src/app/company/[id]/manage_reservation/_styles/CampFilter.module.css
  src/app/company/[id]/manage_reservation/_styles/TotalReservationList.module.css
  src/app/profile/[id]/_components/CompleteModal.tsx
  src/app/profile/[id]/_components/ConfirmModal.tsx
  src/app/profile/[id]/_components/NothingReservation.tsx
  src/app/profile/[id]/_components/ReservationCancelCompleteModal.tsx
  src/app/profile/[id]/_components/ReservationCancelConfirmModal.tsx
  src/app/profile/[id]/_components/ReservationDetail.tsx
  src/app/profile/[id]/_components/ReservationList.tsx
  src/app/profile/[id]/_styles/ReservationCancelCompleteModal.module.css
  src/app/profile/[id]/_styles/ReservationCancelConfirmModal.module.css
  src/app/profile/[id]/_styles/ReservationList.module.css
Labels: 기능수정 🛠, 디자인 🎨

#161 Fix/reservation 예약 스타일 수정
  src/app/camp/detail/[id]/_components/Calendar.tsx
  src/app/camp/detail/[id]/_styles/Calendar.module.css
  src/app/company/[id]/_svg/ResrevationSearchSvg.tsx
  src/app/profile/[id]/_styles/ReservationCancelCompleteModal.module.css
  src/app/profile/[id]/_styles/ReservationCancelConfirmModal.module.css
Labels: 디자인 🎨

#162 Style/camp sort css 수정
  src/app/camp/_components/CampFilter.tsx
  src/app/camp/_styles/Camp.module.css
  src/app/camp/_styles/CampFilter.module.css
  src/app/camp/page.tsx
Labels: 기능 🔧, 디자인 🎨

#164 style/favicon 파비콘 추가
  src/app/community/_components/CommuDragAndDrop.tsx
  src/app/favicon.ico
  src/app/layout.tsx
Labels: 디자인 🎨

#165 og og태그 추가
  src/app/layout.tsx
Labels: 기타

#167 design: 이미지 수정
  src/app/_components/ProfileDivider.tsx
  src/app/_styles/ProfileDiveder.module.css
  src/app/community/_styles/CommuUser.module.css
Labels: 디자인 🎨

#170 리펙토링 hashtag 코드리뷰
  src/app/community/_components/CommuCreateModal.tsx
  src/app/community/_components/CommuEditModal.tsx
  src/app/community/_lib/hashtag.ts
Labels: 리팩토링 ⚙

#171 feat 커뮤니티 무한스크롤구현
  src/app/camp/detail/[id]/_components/KakaoMap.tsx
  src/app/community/_components/CommuPostList.tsx
  src/app/community/page.tsx
Labels: 기능 🔧

#172 fix 삭제시 쿼리키 잘못되어있어서 수정
  src/app/community/_components/CommuPostList.tsx
  src/app/community/_components/CommuUsers.tsx
Labels: 기능수정 🛠, 오류 수정 ❗

#173 Refactor 프로필 그리드 수정
  src/app/community/_components/CommuPhotos.tsx
  src/app/profile/[id]/_styles/MyPost.module.css
Labels: 기능수정 🛠, 디자인 🎨

#174 Refactor:예약 현황 React query 커스텀 훅으로 리팩토링
  src/app/api/company/[id]/reservation/route.ts
  src/app/company/[id]/_lib/getCompanyUserReservation.ts
  src/app/company/[id]/_lib/getTodayReservation.ts
  src/app/company/[id]/manage_reservation/_components/Reservation.tsx
  src/app/company/[id]/manage_reservation/_components/ReservationList.tsx
  src/app/company/[id]/manage_reservation/_components/TotalReservationList.tsx
  src/app/profile/[id]/_components/ReservationDetail.tsx
  src/app/profile/[id]/_components/ReservationList.tsx
  src/app/profile/[id]/_lib/getUserReservation.ts
  src/hooks/useCompanyUserTodayReservationQuery.ts
  src/hooks/useCompanyUserTotalReservationQuery.ts
  src/hooks/useDeleteCompanyUserTotalResevationQuery.ts
  src/hooks/useMyReservationQuery.ts
Labels: 리팩토링 ⚙

#175 Feat/profile 마이페이지 무한스크롤 구현
  src/app/api/profile/[id]/community/user/post/[page]/route.ts
  src/app/profile/[id]/_components/MyPost.tsx
  src/app/profile/[id]/_components/MyPostContent.tsx
  src/app/profile/[id]/_lib/profile.ts
  src/hooks/useIntersectionObserver.ts
  src/hooks/useMyPostQuery.ts
  src/types/profile.ts
Labels: 리팩토링 ⚙, 기능 🔧
